# Generated by Django 5.1.3 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_producto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Segunda mano', 'Segunda mano')], default='Nuevo', max_length=15),
        ),
    ]
