# Generated by Django 5.1.3 on 2024-12-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_producto_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
    ]
