# Generated by Django 5.1.3 on 2024-12-05 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_remove_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Segunda mano', 'Segunda mano')], default='Nuevo', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Campamentos Saharauis', 'Campamentos Saharauis'), ('Tindouf', 'Tindouf'), ('Mauritania', 'Mauritania'), ('España', 'España')], max_length=200, null=True),
        ),
    ]
